[SC-312] update to restrict put object calls
Sage-Bionetworks/service-catalog-library pull request #243
Opened 2021-03-19 16:20 UTC by zaro0508

restrict Put-Object calls to include bucket-owner-full-control
which means users using AWS CLI must upload with
`--acl bucket-owner-full-control`

2021-03-19 17:44 UTC, xschildw approved these changes

2021-03-19 20:40 UTC, brucehoff requested changes
The change in the PR is not what the title and description of the PR indicate:   The change in the PR switches ownership of uploaded objects to be that of the bucket.  The PR title indicates that the change forces the user to add the 'bucket-owner-full-control' ACL to the object (which does not change ownership but which IS a requirement for the BucketOwnershipPreferred setting to cause the ownership to change.)

2021-03-22 13:46 UTC, brucehoff approved these changes
This template doesn't include the bucket policy but I assume the policy includes the requirement that uploaded files give the bucket owner full access control, since that's the other necessary piece.

2021-03-22 16:37 UTC, zaro0508 commented
> This template doesn't include the bucket policy but I assume the policy includes the requirement that uploaded files give the bucket owner full access control, since that's the other necessary piece.

It actually does, it's in the custom resource (Custom::SCS3BucketPolicy).  We manage the bucket policy with that custom resource and the update for it is in the dependent PR https://github.com/Sage-Bionetworks-IT/cfn-cr-sc-bucket-policy/pull/4

2021-03-23 16:45 UTC, BrunoGrandePhD approved these changes

2021-03-25 15:31 UTC, ahayden approved these changes

2021-07-15 21:40 UTC, merged