IT-2735: Move to GHA
Sage-Bionetworks/service-catalog-library pull request #291
Opened 2023-04-24 21:36 UTC by xschildw

This PR replace the Travis deployment by Github actions to push the service catalog templates to S3.

2023-04-26 20:56 UTC, jesusaurus approved these changes

2023-05-18 15:42 UTC, zaro0508 requested changes

2023-05-18 15:42 UTC, zaro0508 commented on .github/workflows/deploy.yaml
> +concurrency:
i don't think you need this

2023-06-07 18:35 UTC, zaro0508 commented
this PR has been replaced with  https://github.com/Sage-Bionetworks/service-catalog-library/pull/293

2023-06-07 18:35 UTC, closed without merging