SC-383: Update utility version
Sage-Bionetworks/service-catalog-library pull request #301
Opened 2023-07-31 15:29 UTC by xschildw

This PR updates the version of service-catalog-utility (to pick up fix on apache .conf rewrite).

Depends on https://github.com/Sage-Bionetworks/service-catalog-utils/pull/22 .

2023-07-31 15:39 UTC, brucehoff approved these changes

2023-07-31 15:54 UTC, zaro0508 requested changes
i think we should just remove this apache rewrite step altogether since it's already being done in [packer-rstudio image](https://github.com/Sage-Bionetworks-IT/packer-rstudio/blob/master/src/proxy.conf).  i think setting it up in packer-rstudio is easier and more maintainable than setting it up with a custom script here.

2023-07-31 16:47 UTC, xschildw commented
Can't do, the file in the image has a placeholder that's replaced at launch time by the instance id (at least for apache conf).

2023-08-01 13:54 UTC, brucehoff approved these changes

2023-08-01 14:17 UTC, merged